### PR TITLE
Potential MakeFile Development Version Changes

### PR DESCRIPTION
**Pull request by thebeline**
The pattern here is based off a number of other sources I found, that suggest including the branch, commit, and distance from master.  As well as an indicator of wether or not the build was off a dirty tree with uncommitted or tracked changes.

There are probably better ways to do this, perhaps with BUILD numbers, or something, but this is just a baseline suggestion.

I feel something needs to be added to track this, if other devs are going to be testing changes for submission.  This is not a final suggestion for 'how', but just an earmark for one way it could be done.

**Of note**:

- If building off branch `master`, the `deb` name is:
  `octoscreen_2.6.1-1_armhf.deb`
- If building off the latest commit in this PR, the name is:
  `octoscreen_2.6.1~IMPDevelopmentVersions+2:c219513-dirty-1_armhf.deb`
  Which indicates:
  - We are on branch `IMPDevelopmentVersions` (slashes removed for sanitization)
  - The branch was, at the time of `Build`, 2 commits ahead of `master` (this is to be considered, as well, 2 commits ahead of the `2.6.1` tag, as those are what is committed to `master`).
  - The latest commit's SHA is `c219513`
  - The working directory was `dirty` at the time of build (contained un-committed or tracked changes)

**Granted:** Not many people are going to be building `deb`s for this on their own, but for those of us who are, having a sane and readable versioning pattern will help A LOT.  :-D

### CODE REVIEW

**Comment by thebeline** [comment]
Of note: The `deb` is marked `dirty` here because I do have an untracked file (I made this branch while working on another branch, so there is an untracked file in my local folder because I am a dirty dirty boy, sorry).

If you were to pull this and do it yourself, you would not get the dirty flag.

**Comment by JeffB42** [comment]
I posted some comments in **https://github.com/Z-Bolt/OctoScreen/issues/242**.  I'm about to release 2.7.0, so I'll look at this after it's been released.

**Comment by thebeline** [comment]
Been looking around a bit, and this SUPER doesn't follow [Semantic Versioning specifications](https://semver.org/), I will have to re-visit this.

That said, I also don't know as `BUILD` really needs to be included in the file name (the existing system doesn't, and it's kind of wonk).

And one last note for myself/you: The `make` sets `-ldflags` on build, and yet they are not used, and the version and/or build are in-fact hard-coded, which is kind of a bummer.  I am going to push a commit to this that makes use of the `-ldflags` a bit more as they are intended to be used, and...  some time after that, I will rejigger the `BUILD` stuffs...  Maybe...  I dunno.  Maybe the date is fine enough...

**Comment by thebeline** [comment]
OH, another note:

There was (not from you, but I inferred from another user in the Issues) some thought about branch naming/conventions and such, and going down the auto-versioning rabbit-hole got me thinking about it.

Perhaps a `development` branch, that receives the release *tag* just prior to merging into `master`, which would make `master` the "stable" branch, and any builds that weren't on branch `master` would be a deviated build from the most recent `tag`, and would receive a modified `build` as such.  All PRs could go to `development` or `dev` or what have you, and occasionally we just increment the minor version when merged things are stable, or the rc version or whatever and. merge to master.  If the latest tag didn't include a `-.*` (such as `-rc1`, or `-alpha`) it automatically adds a `-dev` and sets the build in a verbose way.  If it does include a `-.*`, it sets the `build` in a deviation way.

Hrmph...  I'm gonna think on it summore.

**Comment by thebeline** [comment]
Meh

**Pull request closed without merging**
